#
#  This file is part of SplashSync Project.
#
#  Copyright (C) 2015-2019 Splash Sync  <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#

version: '2'

services:
    odoo:
        image:  odoo:latest
        depends_on:
            - db
        ports:
            - "8069:8069"
        volumes:
            - ./src:/mnt/extra-addons/splashsync:ro
            - ../SplashSync-Py-Core/splashpy:/mnt/extra-addons/splashpy:ro
            - ../SplashSync-Py-Core:/mnt/splashpy
    db:
        image: postgres:10
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
