
splash:

################################################################################
# Configure Splash Bundle Parameters Cache
# Cache is Enabled by Default to Store Custom Connectors Configuration
# If disabled, configuration must be store in Static, on connections section
################################################################################
    cache:
        enabled: true
        lifetime: 10

    # Allow Notifications for Generic Users
    notify: ["ROLE_USER"]

################################################################################
# List of Availables Connector Connections
################################################################################

    connections:

        ########################################################################
        # Odoo Connection
        odoo:
            id:                 ThisIsSplashWsId
            key:                ThisIsYourEncryptionKeyForSplash
            name:               Odoo Server
            host:               false
            connector:          soap
            config:
                WsIdentifier:       ThisIsSplashWsId
                WsEncryptionKey:    ThisIsYourEncryptionKeyForSplash
                WsHost:             http://odoo:8069
                WsPath:             /splash
                Name:               Odoo dev
